In [2]:
import exploration
import pandas as pd
import datetime
from datetime import datetime

In [3]:
path_outcomes = "../outcomes/outcomes.csv"
df_outcomes = exploration.read_data(path_outcomes, index_col = "projectid")
path_projects = "../projects/projects.csv"
df_projects = exploration.read_data(path_projects, index_col = "projectid")

In [14]:
df_outcomes.head()

,is_exciting,at_least_1_teacher_referred_donor,fully_funded,at_least_1_green_donation,great_chat,three_or_more_non_teacher_referred_donors,one_non_teacher_referred_donor_giving_100_plus,donation_from_thoughtful_donor,great_messages_proportion,teacher_referred_count,non_teacher_referred_count
projectid,,,,,,,,,,,
ffffc4f85b60efc5b52347df489d0238,f,NaN,f,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN
ffffac55ee02a49d1abc87ba6fc61135,f,f,t,t,f,t,f,f,57.0,0.0,7.0
ffff97ed93720407d70a2787475932b0,f,f,t,t,t,t,t,f,100.0,0.0,3.0
ffff418bb42fad24347527ad96100f81,f,f,f,t,t,f,f,f,100.0,0.0,1.0
ffff2d9c769c8fb5335e949c615425eb,t,t,t,t,t,f,t,f,63.0,6.0,2.0

In [5]:
df_projects.head()

,teacher_acctid,schoolid,school_ncesid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,school_district,...,resource_type,poverty_level,grade_level,fulfillment_labor_materials,total_price_excluding_optional_support,total_price_including_optional_support,students_reached,eligible_double_your_impact_match,eligible_almost_home_match,date_posted
projectid,,,,,,,,,,,,,,,,,,,,,
316ed8fb3b81402ff6ac8f721bb31192,42d43fa6f37314365d08692e08680973,c0e6ce89b244764085691a1b8e28cb81,6.362701e+10,36.576340,-119.608713,Selma,CA,93662.0,NaN,Selma Unified Sch District,...,Books,highest poverty,Grades 6-8,30.0,555.81,653.89,32.0,f,f,2014-05-12
90de744e368a7e4883223ca49318ae30,864eb466462bf704bf7a16a585ef296a,d711e47810900c96f26a5d0be30c446d,4.837020e+11,32.911179,-96.723640,Dallas,TX,75243.0,urban,Richardson Ind School District,...,Books,highest poverty,Grades PreK-2,30.0,296.47,348.79,22.0,f,f,2014-05-12
32943bb1063267de6ed19fc0ceb4b9a7,37f85135259ece793213aca9d8765542,665c3613013ba0a66e3a2a26b89f1b68,4.103270e+11,45.166039,-122.414576,Colton,OR,97017.0,rural,Colton School District 53,...,Technology,high poverty,Grades PreK-2,30.0,430.89,506.93,17.0,f,f,2014-05-11
bb18f409abda2f264d5acda8cab577a9,2133fc46f951f1e7d60645b0f9e48a6c,4f12c3fa0c1cce823c7ba1df57e90ccb,3.600153e+11,40.641727,-73.965655,Brooklyn,NY,11226.0,urban,New York City Dept Of Ed,...,Books,highest poverty,Grades 3-5,30.0,576.07,677.73,12.0,f,f,2014-05-11
24761b686e18e5eace634607acbcc19f,867ff478a63f5457eaf41049536c47cd,10179fd362d7b8cf0e89baa1ca3025bb,6.227100e+10,34.043939,-118.288371,Los Angeles,CA,90006.0,urban,Los Angeles Unif Sch Dist,...,Other,highest poverty,Grades PreK-2,30.0,408.40,480.47,24.0,f,f,2014-05-11

In [6]:
df_projects["date_posted"] = pd.to_datetime(df_projects["date_posted"])

In [7]:
date_lb = pd.Timestamp(datetime(2012, 1, 1))
date_ub = pd.Timestamp(datetime(2013, 12, 31))

In [8]:
date_filter = (df_projects["date_posted"] >= date_lb) & (df_projects["date_posted"] <= date_ub)

In [9]:
df_projects = df_projects[date_filter].copy()

In [10]:
df_projects["date_posted"].describe()

count                  248955
unique                    731
top       2012-09-30 00:00:00
freq                     1490
first     2012-01-01 00:00:00
last      2013-12-31 00:00:00
Name: date_posted, dtype: object

In [21]:
df = df_projects.join(df_outcomes)
df = df.drop(["teacher_acctid", "schoolid", "school_ncesid", "school_latitude", "school_longitude","school_city", "school_state", "school_district", "school_county", "teacher_prefix", "date_posted"], axis = 1).copy()

In [22]:
df.count()

school_zip                                        248955
school_metro                                      218567
school_charter                                    248955
school_magnet                                     248955
school_year_round                                 248955
school_nlns                                       248955
school_kipp                                       248955
school_charter_ready_promise                      248955
teacher_teach_for_america                         248955
teacher_ny_teaching_fellow                        248955
primary_focus_subject                             248927
primary_focus_area                                248927
secondary_focus_subject                           168297
secondary_focus_area                              168297
resource_type                                     248921
poverty_level                                     248955
grade_level                                       248951
fulfillment_labor_materials                       248955
total_price_excluding_optional_support            248955
total_price_including_optional_support            248955
students_reached                                  248863
eligible_double_your_impact_match                 248955
eligible_almost_home_match                        248955
is_exciting                                       248955
at_least_1_teacher_referred_donor                 216810
fully_funded                                      248955
at_least_1_green_donation                         216810
great_chat                                        248955
three_or_more_non_teacher_referred_donors         216810
one_non_teacher_referred_donor_giving_100_plus    216810
donation_from_thoughtful_donor                    216810
great_messages_proportion                         209006
teacher_referred_count                            216810
non_teacher_referred_count                        216810
dtype: int64

In [23]:
df.head()

,school_zip,school_metro,school_charter,school_magnet,school_year_round,school_nlns,school_kipp,school_charter_ready_promise,teacher_teach_for_america,teacher_ny_teaching_fellow,...,at_least_1_teacher_referred_donor,fully_funded,at_least_1_green_donation,great_chat,three_or_more_non_teacher_referred_donors,one_non_teacher_referred_donor_giving_100_plus,donation_from_thoughtful_donor,great_messages_proportion,teacher_referred_count,non_teacher_referred_count
projectid,,,,,,,,,,,,,,,,,,,,,
62526d85d2a1818432d03d600969e99c,60103.0,suburban,f,f,f,f,f,f,f,f,...,f,t,f,t,t,t,f,80.0,0.0,6.0
33d59ac771b80222ad63ef0f4ac47ade,83402.0,urban,f,f,f,f,f,f,f,f,...,NaN,f,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN
1a3aaeffc56dd2a421e37d8298024c0a,3038.0,suburban,f,f,f,f,f,f,f,f,...,f,f,t,f,f,f,f,NaN,0.0,2.0
33aa19ee4da4c5adf47d0dfb84fab5ef,23224.0,urban,f,f,f,f,f,f,f,f,...,f,f,t,f,f,f,f,NaN,0.0,1.0
e31c0ea8b68f404699dfb0d39e9bc99b,60613.0,urban,f,t,f,f,f,f,f,f,...,f,t,t,f,f,t,f,50.0,0.0,2.0